### ISSUE TITLE
Add support for BAN.

### ISSUE THREAD

**Issue by lpeabody** [docksal/service-varnish#13]
Drupal 8 supports cache tags and it would be nice to have support for BAN so we can do our Varnish testing locally https://www.drupal.org/docs/8/api/cache-api/cache-tags-varnish.

**Comment by sergey-zabolotny** [comment]
https://github.com/docksal/service-varnish/pull/15

**Comment by lmakarov** [comment]
Closed via https://github.com/docksal/service-varnish/pull/16
