### ISSUE TITLE
Add proper tests for BAN

### ISSUE THREAD

**Issue by lmakarov** [docksal/service-varnish#20]
There are currently two identical tests for `PURGE` but none for `BAN` in `test.bats`.

We need:
- a test added to `BAN`
- Docs for how to use `BAN` (as well as `PURGE`) in README

**Comment by sergey-zabolotny** [comment]
Added tests in https://github.com/docksal/service-varnish/pull/23

**Comment by lmakarov** [comment]
@sergey-zabolotny please also update the README with the description and examples of how cache purging can be done.
