### ISSUE TITLE
docksal/varnish:latest should be pushed for builds on master or release tags

### ISSUE THREAD

**Issue by lmakarov** [docksal/service-varnish#21]
`docksal/varnish:latest` is pushed for builds on `develop`. Instead it should be pushed for builds on `master` and/or release tags.

**Comment by sergey-zabolotny** [comment]
we have 2 versions of varnish. it should looks like 4.1-latest/5.2-latest (something else) or both?

**Comment by sergey-zabolotny** [comment]
fixed in https://github.com/docksal/service-varnish/pull/22
