### ISSUE TITLE
Make Cache-Tags header (used for BAN requests) configurable

### ISSUE THREAD

**Issue by lmakarov** [docksal/service-varnish#24]
We should make the header used for BAN requests configurable as there seems to be no standard for it.

- [These docs on d.o](https://www.drupal.org/docs/8/api/cache-api/cache-tags-varnish) suggest `X-Cache-Tags` header should be used
- [Purger module](https://www.drupal.org/node/2692523) uses `Purge-Cache-Tags` header by default
- [Acquia Purge](https://www.drupal.org/project/acquia_purge) uses `X-Acquia-Purge-Tags`
- [Wodby](https://wodby.com/docs/stacks/drupal/containers/#drupal-8) sticks with the `Cache-Tags` header
- (Symfony FOSHttpCache)[https://foshttpcache.readthedocs.io/en/stable/varnish-configuration.html#ban] uses `X-Cache-Tags`

Let's call the variable `VARNISH_CACHE_TAGS_HEADER`  and have `Cache-Tags` (as is now) as the default value.

README should also be updated to mention this usage and configuration of this header.

**Comment by sergey-zabolotny** [comment]
Fixed in https://github.com/docksal/service-varnish/pull/25
