### ISSUE TITLE
Possibility as global service

### ISSUE THREAD

**Issue by erik-seifert** [docksal/service-varnish#39]
Is it possible to use this service global? We use docksal for our dev and stage environments and want to share some ressources for all projects.

**Comment by achekulaev** [comment]
There is no automatic support for global services besides the Docksal system containers. 

Of course you can run a service yourself with `docker` command, but then you would need to manually connect (disconnect) it to (from) the projects' networks.

**Comment by erikseifert** [comment]
So we can close this ;- )
